### ISSUE TITLE
CAS SSO and CASinoApp - NameError

### ISSUE THREAD

**Issue by adundovi** [eriko/cas_sso#1]
I'm trying to employ CAS SSO and CASinoApp for Discourse's LDAP login. CASinoApp is probably successfully set up because it works with other CAS-enabled applications. So I deduce that the problem could be in CAS SSO plugin but I don't know Ruby enough that I could debug it by myself.

After a successful authorization, I get blank screen on /auth/cas/callback... route. Discourse log says:
```
!! NameError (wrong constant name #<Class:0x007faf739c77d0>)
```

And a relevant part of traceback is probably:
```
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/module/qualified_const.rb:30:in `const_defined?'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/module/qualified_const.rb:30:in `block in qualified_const_defined?'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/module/qualified_const.rb:29:in `each'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/module/qualified_const.rb:29:in `inject'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/module/qualified_const.rb:29:in `qualified_const_defined?'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:362:in `qualified_const_defined?'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:464:in `load_missing_constant'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:180:in `const_missing'
/var/www/discourse/plugins/discourse-cas-plugin/plugin.rb:24:in `after_authenticate'
/var/www/discourse/app/controllers/users/omniauth_callbacks_controller.rb:38:in `complete'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
/var/www/discourse/vendor/bundle/ruby/2.0.0/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
(...)
```

env context:
```
HTTP_HOST: community.example.com
REQUEST_URI: /auth/cas/callback?url=https%3A%2F%2Fcommunity.example.com%2F&ticket=ST-14240784023377-k5ORYWfjwJxYe1FXh1FZBTASQQDsmhDl03L8myBB
REQUEST_METHOD: GET
HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_REFERER: https://community.example.com/
HTTP_X_FORWARDED_FOR: y.y.y.y, x.x.x.x
HTTP_X_REAL_IP: x.x.x.x

params:
  url: https://community.example.com/
  ticket: ST-14240784023377-k5ORYWfjwJxYe1FXh1FZBTASQQDsmhDl03L8myBB
```

Here is the XML output after auth from CAS:
```
<cas:serviceResponse>
 <cas:authenticationSuccess>
    <cas:user>MyUsername</cas:user>
    <cas:attributes><cas:authenticationDate>2015-02-16T08:19:42Z</cas:authenticationDate>
    <cas:longTermAuthenticationRequestTokenUsed>false</cas:longTermAuthenticationRequestTokenUsed><cas:isFromNewLogin>true</cas:isFromNewLogin>
    <cas:email>mail@exmaple.com</cas:email><cas:fullname>Andrej</cas:fullname>
    <cas:domainmail>myusername@mydomain.com</cas:domainmail></cas:attributes>
  </cas:authenticationSuccess>
</cas:serviceResponse>
```

Discourse is installed in typical docker installation with one more nginx forwarding request to it.

Thank you,
//Andrej

**Comment by eriko** [comment]
I need to deprecate this project here.  I have already noted at the end of the topic on meta to switch to the cas app the uses the SSO features of discourse.  Since you have setup casino this should ne pretty easy for you to setup  It can run suburi if you need it.
https://github.com/eriko/discourse_cas_sso

**Comment by eriko** [comment]
My response was a bit rude as I was just finishing up vacation and figured you would want a response sooner rather than later.  I hope you did not take offense.

**Comment by adundovi** [comment]
Eriko, your answer is just fine. I understand that you cannot handle support for deprecated projects. I reported this issue because I didn't see that cas_sso is deprecated.

But your suggestion that I should use SSO app, which is the successor of this project, is not suited for me because, as I understood, Discourse's SSO auth disables all other auth techniques (Google, Facebook, Twitter and etc.) which is not an option in my case. I'll try to write my own LDAP plugin with omniauth-ldap gem. I don't know Ruby, but I should be give it a chance. :-)

**Comment by eriko** [comment]
This issue that you are going to have is that the plugin way of doing it still requires that something else does the login interface.  In other words the plugin delegates logging in to some other app and then gets back a nay or a yay with a username.

This is, I thiny, why no one has built a ldap login.
